apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      nodePort: 30007
    - name: bolt
      port: 7687
      targetPort: 7687
      nodePort: 30008
  selector:
    app: neo4j
