apiVersion: v1
kind: Service
metadata:
  name: langfuse-service
spec:
  selector:
    app: langfuse
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30006
  type: NodePort